apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-auto-backup-db
spec:
  # the cronjob will be activated at every night at midnight
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-bot
            image: liupengfei99/db_backup_restore:main
            imagePullPolicy: IfNotPresent
            env:
              - name: BACKUP_DIR
                value: "s3://pengfei/tmp/sql_backup"
            envFrom:
            - configMapRef:
                name: dbsavior-job-init-configmap
            - secretRef:
                name: dbsavior-job-s3-secrets
            command: [sh, -c]
            args: ["python dbsavior/main.py --db_type postgres --storage_type s3 --action auto_backup --db_login $DB_LOGIN 
                --db_pwd $DB_PWD --db_host $DB_HOST --db_port $DB_PORT
                --backup_dir $BACKUP_DIR --target_db $TARGET_DB"]
          restartPolicy: OnFailure