apiVersion: batch/v1
kind: Job
metadata:
  name: populate-db
  labels:
    app: db-backup-restore
spec:
  template:
    spec:
      containers:
        - name: populate-bot
          image: liupengfei99/db_backup_restore:main
          env:
            - name: AWS_ACCESS_KEY_ID # your s3 server access key id
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY # your s3 server secret key
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: secretKey
            # The token is optional based on your s3 creds type, you can leave it empty
            - name: AWS_SESSION_TOKEN
              value: ""    # your s3 server access token, example:
          envFrom:
            - configMapRef:
                name: sql-lesson-init-configmap
          command: [sh, -c]
          args: ["python dbsavior/main.py --db_type postgres --storage_type s3 --action populate --db_login $DB_LOGIN 
                --db_pwd $DB_PWD --db_host $DB_HOST --db_port $DB_PORT
                --backup_file $BACKUP_FILE --target_db $TARGET_DB"]
      restartPolicy: Never
  completions: 1

  parallelism: 1
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 150
  backoffLimit: 4