apiVersion: batch/v1
kind: Job
metadata:
  name: auto-restore-db
  labels:
    app: db-backup-restore
spec:
  template:
    spec:
      containers:
        - name: restore-bot
          image: liupengfei99/db_backup_restore:main
          imagePullPolicy: Always
          env:
            - name: BACKUP_DIR
              value: "changeMe" # the parent directory that you want to store your backup files, example: s3://pengfei/tmp/sql_backup
          envFrom:
            - configMapRef:
                name: dbsavior-job-init-configmap
            - secretRef:
                name: dbsavior-job-s3-secrets
          command: [sh, -c]
          args: ["python dbsavior/main.py --db_type postgres --storage_type s3 --action auto_restore --db_login $DB_LOGIN 
                  --db_pwd $DB_PWD --db_host $DB_HOST --db_port $DB_PORT
                  --backup_dir $BACKUP_DIR --target_db $TARGET_DB"]
      restartPolicy: Never
  completions: 1
  parallelism: 1
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 150
  backoffLimit: 4